language: python
python:
    - "2.7"
    - "3.4"
    - "3.5"
    - "3.6"
install:
    - pip install pygame numpy cython pytest psutil
    - pip install ./accelerate
    - pip install .

script: xvfb-run pytest -v tests/*
