language: python
python:
    - "2.7"
    - "3.4"
    - "3.5"
    - "3.6"
install:
    - pip install pygame numpy cython pytest psutil
    - pip install ./accelerate
    - pip install .

before_script:
  - xvfb-run -s "-screen 0 640x480x24 +extension GLX +extension RENDER" glxinfo
  
script: xvfb-run -s "-screen 0 640x480x24 +extension GLX +extension RENDER" pytest -v tests
